/* ──────────────────────────────────────────────────────────
   Template "stand-in" models shown during onboarding so a user
   can finish — and even run a real try-on — BEFORE uploading
   their own photo. They pick the closest model by gender + a
   rough BMI bucket, and are nudged to swap in their own photo
   later. Assets are generated by scripts/gen-models.mjs and
   live in /public/images/models/.
   ────────────────────────────────────────────────────────── */

import type { UserProfile } from "./store";

export type Build = "slim" | "medium" | "full";
type ModelGender = "female" | "male";

const BUILDS: Build[] = ["slim", "medium", "full"];

/** Rough build bucket from BMI. No measurements → "medium". */
export function buildFromMeasurements(heightCm?: number | null, weightKg?: number | null): Build {
  if (!heightCm || !weightKg) return "medium";
  const h = heightCm / 100;
  const bmi = weightKg / (h * h);
  if (bmi < 20) return "slim";
  if (bmi < 26) return "medium";
  return "full";
}

/** We only ship female/male sets; unknown/other defaults to female. */
function modelGender(gender: UserProfile["gender"]): ModelGender {
  return gender === "male" ? "male" : "female";
}

export function templateModelSrc(gender: UserProfile["gender"], build: Build): string {
  return `/images/models/model-${modelGender(gender)}-${build}.jpg`;
}

/** The best stand-in model path for a profile's gender + measurements. */
export function pickTemplateModel(
  gender: UserProfile["gender"],
  heightCm?: number | null,
  weightKg?: number | null,
): string {
  return templateModelSrc(gender, buildFromMeasurements(heightCm, weightKg));
}

/** All builds for a gender — used to let the user pick a different stand-in. */
export function templateModelsFor(gender: UserProfile["gender"]): { build: Build; src: string }[] {
  return BUILDS.map((build) => ({ build, src: templateModelSrc(gender, build) }));
}

/** Is this photo one of our shipped template stand-ins (vs the user's own)? */
export function isTemplateSrc(src: string | null | undefined): boolean {
  return !!src && src.startsWith("/images/models/model-");
}
